[project]
name = "Cryptonomers"
authors = []
description = ""
telemetry = false
requirements = []
analysis = ["check_checker"]
costs_version = 2

[contracts.digital_will]
path = "contracts/digital_will.clar"
depends_on = []
